name: .NET Build and Test

on:
  push:
    branches:
    - main
    - develop
  pull_request:

env:
  JAVA_VERSION: 21
  DOTNET_VERSION: 10.0.x

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      # Note: The database name may be overridden by the tests
      CONNECTION_STRING: 'Server=localhost,1433;Database=integrationtests;User Id=sa;Password=P1swrd!$;TrustServerCertificate=True;integrated security=false;'
      CONNECTION_STRING_KEY: 'ConnectionStrings:DefaultConnection'

    services:
      sql-server:
        image: mcr.microsoft.com/mssql/server@sha256:ea73825f3d88a23c355ac2f9fdc6bd960fec90171c12c572109b36a558f77bb8
        ports:
        - 1433:1433
        env:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: P1swrd!$

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0 # Shallow clones disabled for a better relevancy of SC analysis

      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@d9cee638f295eca3c446655c8785a383cf94bbc3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'microsoft'

      - name: Add nuget package source
        run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/DFE-Digital/index.json"

      - name: Cache SonarCloud packages
        uses: actions/cache@a7833574556fa59680c1b7cb190c1735db73ebf0 # v5.0.0
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Install SonarCloud scanners
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Install dotnet reportgenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Restore dependencies
        run: dotnet restore Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.sln

      - name: Build solution, test and run SonarCloud scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet-sonarscanner begin /k:"DFE-Digital_manage-free-schools-projects" /o:"dfe-digital" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /s:${{ github.workspace }}/SonarQube.Analysis.xml
          dotnet build Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.sln --no-restore
          dotnet test Dfe.ManageFreeSchoolProjects/Dfe.ManageFreeSchoolProjects.sln --no-build --verbosity normal --collect:"XPlat Code Coverage" --environment "${{ env.CONNECTION_STRING_KEY }}"="${{ env.CONNECTION_STRING }}"
          reportgenerator -reports:"./**/coverage.cobertura.xml" -targetdir:./Dfe.ManageFreeSchoolProjects/CoverageReport -reporttypes:SonarQube
          dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
